version: "3"
   
services:
  app:
    image: quay.io/dtan4/terraforming:latest
    volumes: 
      - ~/.aws:/root/.aws
    command: ["tail", "-f", "/dev/null"]
    environment: 
      AWS_PROFILE: <AWS_PROFILE>
      AWS_REGION: ap-southeast-1
